### ISSUE TITLE
Experiments run slowly on V100

### ISSUE THREAD

**Issue by xiamengzhou** [huggingface/nn_pruning#28]
Hi thanks for sharing this great work! I am trying to train a model on my own with the hybrid filled setting for MNLI and it seems that it takes more than 5 hours to train for one epoch. Is the training expected to be this slow or there might be something run with what I do? I basically use the same hyperparameters provided in the analysis folder.

**Comment by xiamengzhou** [comment]
I accidentally set the nrows to be 1, by setting it to 32 it's much faster.

**Comment by iMountTai** [comment]
@xiamengzhou Does this script run with the hybrid-filled method by default?Thanks!
